name: plugin_indirect_lints
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  analyzer: ^5.4.0
  analyzer_plugin: ^0.11.2
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
